workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"

  stages:
    - build
    - test

build-job:
  stage: build
  image: eclipse-temurin:21-jdk
    - target/*.jar
    expire_in: 1 week

# SAST (пз 3)
sast-semgrep:
  stage: test
  image: semgrep/semgrep  # Используем обновленный образ
  tags:
    - linux
    - bas2301
  artifacts:
    reports:
      sast: report.sarif
    paths:
      - report.sarif
# SCA (пз 4)
sca-dependency-check:
  stage: test
  image: maven:3.9-eclipse-temurin-21
  tags:
    - linux
    - bas2301
  script:
    - chmod +x mvnw
    - ./mvnw dependency-check:check
  artifacts:
    paths:
